# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: tugo/leads/v1/lead.proto for package 'tugo.leads.v1'

require 'grpc'
require 'tugo/leads/v1/lead_pb'

module Tugo
  module Leads
    module V1
      module LeadService
        class Service

          include ::GRPC::GenericService

          self.marshal_class_method = :encode
          self.unmarshal_class_method = :decode
          self.service_name = 'tugo.leads.v1.LeadService'

          rpc :GetLeadList, ::Google::Protobuf::Empty, ::Tugo::Leads::V1::LeadListResponse
        end

        Stub = Service.rpc_stub_class
      end
    end
  end
end
