campaigns:
  host: <%= ENV.fetch('CAMPAIGNS_HOST') { 'tugo_campaigns_app_1:50051' } %>

common:
  host: <%= ENV.fetch('COMMON_HOST') { 'tugo_common_app_1:50051' } %>

leads:
  host: <%= ENV.fetch('LEADS_HOST') { 'tugo_leads_app_1:50051' } %>

organizations:
  host: <%= ENV.fetch('ORGANIZATIONS_HOST') { 'tugo_organizations_app_1:50051' } %>

env:
  name: <%= ENV['ENV_NAME'] %>
