# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: tugo/campaigns/v1/campaign.proto for package 'tugo.campaigns.v1'

require 'grpc'
require 'tugo/campaigns/v1/campaign_pb'

module Tugo
  module Campaigns
    module V1
      module CampaignService
        class Service

          include ::GRPC::GenericService

          self.marshal_class_method = :encode
          self.unmarshal_class_method = :decode
          self.service_name = 'tugo.campaigns.v1.CampaignService'

          rpc :GetCampaignList, ::Google::Protobuf::Empty, ::Tugo::Campaigns::V1::CampaignListResponse
        end

        Stub = Service.rpc_stub_class
      end
    end
  end
end
