# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tugo/campaigns/v1/campaign.proto

require 'google/protobuf'

require 'google/protobuf/empty_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("tugo/campaigns/v1/campaign.proto", :syntax => :proto3) do
    add_message "tugo.campaigns.v1.CampaignListResponse" do
      repeated :campaigns, :message, 1, "tugo.campaigns.v1.Campaign"
    end
    add_message "tugo.campaigns.v1.Campaign" do
      optional :id, :int64, 1
      optional :campaign_name, :string, 2
      optional :campaign_type, :int32, 3
      optional :campaign_status, :int32, 4
      optional :expected_revenue, :int64, 5
      optional :closing_date, :string, 6
    end
  end
end

module Tugo
  module Campaigns
    module V1
      CampaignListResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tugo.campaigns.v1.CampaignListResponse").msgclass
      Campaign = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tugo.campaigns.v1.Campaign").msgclass
    end
  end
end
