# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: tugo/common/v1/employee.proto for package 'tugo.common.v1'

require 'grpc'
require 'tugo/common/v1/employee_pb'

module Tugo
  module Common
    module V1
      module EmployeeService
        class Service

          include ::GRPC::GenericService

          self.marshal_class_method = :encode
          self.unmarshal_class_method = :decode
          self.service_name = 'tugo.common.v1.EmployeeService'

          rpc :GetEmployeeList, ::Google::Protobuf::Empty, ::Tugo::Common::V1::EmployeeListResponse
          rpc :GetEmployeeByNumber, ::Tugo::Common::V1::EmployeeNumber, ::Tugo::Common::V1::Employee
          rpc :GetEmployeeById, ::Tugo::Common::V1::EmployeeId, ::Tugo::Common::V1::Employee
        end

        Stub = Service.rpc_stub_class
      end
    end
  end
end
