# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tugo/contacts/v1/contact.proto

require 'google/protobuf'

require 'google/protobuf/empty_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("tugo/contacts/v1/contact.proto", :syntax => :proto3) do
    add_message "tugo.contacts.v1.ContactListResponse" do
      repeated :contacts, :message, 1, "tugo.contacts.v1.Contact"
    end
    add_message "tugo.contacts.v1.Contact" do
      optional :id, :int64, 1
      optional :last_name, :string, 2
      optional :first_name, :string, 3
      optional :phone, :string, 4
      optional :email, :string, 5
      optional :gender, :int32, 6
      optional :organization_name, :string, 7
    end
  end
end

module Tugo
  module Contacts
    module V1
      ContactListResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tugo.contacts.v1.ContactListResponse").msgclass
      Contact = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tugo.contacts.v1.Contact").msgclass
    end
  end
end
