# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: tugo/contacts/v1/contact.proto for package 'tugo.contacts.v1'

require 'grpc'
require 'tugo/contacts/v1/contact_pb'

module Tugo
  module Contacts
    module V1
      module ContactService
        class Service

          include ::GRPC::GenericService

          self.marshal_class_method = :encode
          self.unmarshal_class_method = :decode
          self.service_name = 'tugo.contacts.v1.ContactService'

          rpc :GetContactList, ::Google::Protobuf::Empty, ::Tugo::Contacts::V1::ContactListResponse
        end

        Stub = Service.rpc_stub_class
      end
    end
  end
end
