# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tugo/contacts/v1/contact.proto

require 'google/protobuf'

require 'google/protobuf/empty_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("tugo/contacts/v1/contact.proto", :syntax => :proto3) do
    add_message "tugo.contacts.v1.ContactIdRequest" do
      optional :contact_id, :int64, 1
    end
    add_message "tugo.contacts.v1.ContactOwnerIdRequest" do
      optional :contact_owner_id, :int64, 1
    end
    add_message "tugo.contacts.v1.UpsertContactRequest" do
      optional :contact, :message, 1, "tugo.contacts.v1.Contact"
    end
    add_message "tugo.contacts.v1.ContactResponse" do
      optional :contact, :message, 1, "tugo.contacts.v1.Contact"
    end
    add_message "tugo.contacts.v1.ContactListResponse" do
      repeated :contacts, :message, 1, "tugo.contacts.v1.Contact"
    end
    add_message "tugo.contacts.v1.UpsertContactResponse" do
      optional :contact, :message, 1, "tugo.contacts.v1.Contact"
    end
    add_message "tugo.contacts.v1.Contact" do
      optional :id, :int64, 1
      optional :first_name, :string, 2
      optional :last_name, :string, 3
      optional :email, :string, 4
      optional :phone, :string, 5
      optional :title, :string, 6
      optional :creator_id, :int64, 7
      optional :owner_id, :int64, 8
      optional :modified_by_id, :int64, 9
      optional :master_leadsource_id, :int64, 10
      optional :is_converted_from_lead, :bool, 11
      optional :is_do_not_call, :bool, 12
      optional :source, :string, 13
      optional :description, :string, 14
      optional :created_at, :string, 15
      optional :updated_at, :string, 16
    end
  end
end

module Tugo
  module Contacts
    module V1
      ContactIdRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tugo.contacts.v1.ContactIdRequest").msgclass
      ContactOwnerIdRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tugo.contacts.v1.ContactOwnerIdRequest").msgclass
      UpsertContactRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tugo.contacts.v1.UpsertContactRequest").msgclass
      ContactResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tugo.contacts.v1.ContactResponse").msgclass
      ContactListResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tugo.contacts.v1.ContactListResponse").msgclass
      UpsertContactResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tugo.contacts.v1.UpsertContactResponse").msgclass
      Contact = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tugo.contacts.v1.Contact").msgclass
    end
  end
end
